name = "fetch-data-belajar-sync"
main = "src/index.js"
compatibility_date = "2024-08-01"

# Cloudflare Workers Configuration
[[d1_databases]]
binding = "DB"
database_name = "api-sekolah-db"
database_id = "9285cac8-f9fc-4aa9-a523-59c603481d0a"
