name: 1. Tarik Data Pondasi (DevAPI)

on:
  workflow_dispatch: # Hanya dijalankan manual dengan klik tombol klik 'Run workflow'

jobs:
  run-pondasi:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari repository
        uses: actions/checkout@v3

      - name: Siapkan Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install module PostgreSQL
        run: npm install

      - name: Jalankan Skrip Pondasi
        run: node tarik-devapi.js
